### ISSUE TITLE
弄成gitbook会不会更好呢？

### ISSUE THREAD

**Issue by shinvdu** [rsj217/translate#1]

**Comment by rsj217** [comment]
当然，不过没有仔细校对，还是比较初始的版本，弄成gitbook容易误人子弟 ：）

2016-08-24 23:20 GMT+08:00 Silas Xie <notifications@github.com>:

**Comment by lilyLi1993** [comment]
好期待12章后面的内容！

**Comment by rsj217** [comment]
原书已经有别人翻译出版了《Elixir程序设计》，我自己的笔记放在 http://www.jianshu.com/collection/e7cab9407e1a
